# Relationale Datenbanken und SQL

Eine relationale Datenbank ist eine Sammlung von Datenobjekten mit vordefinierten Beziehungen zwischen ihnen. Diese Objekte sind als eine Reihe von Tabellen mit Spalten und Zeilen organisiert ([AWS](https://aws.amazon.com/relational-database/?nc1=h_ls)):

- *Tabellen* werden verwendet, um Informationen über die in der Datenbank darzustellenden Objekte zu speichern.
- Jede *Spalte* in einer Tabelle enthält eine bestimmte Art von Daten, und ein Feld speichert den tatsächlichen Wert eines Attributs.
- Die *Zeilen* in der Tabelle stellen eine Sammlung verwandter Werte eines Objekts oder einer Entität dar.
- Jede Zeile in einer Tabelle kann mit einem eindeutigen Bezeichner, dem *Primärschlüssel*, markiert werden, und Zeilen in mehreren Tabellen können mithilfe von *Fremdschlüsseln* miteinander in Beziehung gesetzt werden.

Was ist eine relationale Datenbank:

<br>

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/OqjJjpjDRLc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br>

Diese Daten können auf viele verschiedene Arten (z.B. mit SQL) abgerufen werden. **Structured Query Language** (SQL, ausgesprochen "S-Q-L" oder manchmal "Sequel") ist eine der grundlegendsten Fähigkeiten, die Sie im Umgang mit Daten beherrschen sollten. Es ermöglicht Ihnen, effizient mit Datenbanken zu interagieren, Daten abzurufen und zu manipulieren sowie komplexe Abfragen und Analysen durchzuführen. 

Im nächsten Abschnitt werden wir uns mit der Einrichtung und Verwendung von MySQL und PostgreSQL befassen. Diese relationalen Datenbankmanagementsysteme (RDBMS) sind weit verbreitet und bieten robuste und leistungsstarke Lösungen für die Datenverwaltung.

Wir werden die folgenden Themen behandeln:

- Installation und Konfiguration von MySQL und PostgreSQL
- Grundlegende Befehle und Abfragen in MySQL und PostgreSQL
- Integration dieser Systeme mit Python

Diese Kenntnisse werden Ihnen helfen, Ihre Daten effizient zu verwalten und komplexe Datenanalysen durchzuführen, indem Sie die Stärken dieser RDBMS in Kombination mit der Flexibilität und Leistungsfähigkeit von Python nutzen.