project:
  type: book

lang: de

execute:
  freeze: auto

book:
  title: "Data Science, AI & Analytics Toolkit"
  description: "Programming Toolkit für Data Science, AI & Analytics"

  image: "/images/logo.png"
  favicon: "/images/logo.png"
  search:
    type: overlay  
  page-footer:
    left: |
      © [Jan Kirenz](https://www.kirenz.com/), 2024

  chapters:
    - index.qmd

    - part: erste-schritte/index.qmd
      chapters:
        - erste-schritte/projektumgebung.qmd 
        - erste-schritte/python-installation.qmd
        - erste-schritte/python-idle.qmd
        - erste-schritte/anaconda-installation.qmd
        - erste-schritte/jupyter-notebook.qmd
        - erste-schritte/markdown.qmd

    - part: python/index.qmd
      chapters:
        - text: "Bibliotheken"
          href: python/python-bibliotheken.qmd
        - text: "Umgebungen"
          href: python/python-umgebung.qmd
        - python/python-arbeitsbereich.qmd
        - python/python-basics.qmd
        - python/python-einrueckung.qmd
       # - python/python-funktionen.qmd
       # - python/python-kontrollstrukturen.qmd
       # - python/python-klassen.qmd

    - part: vscode/index.qmd
      chapters:
        - vscode/visual-studio-code-installation.qmd
        - vscode/visual-studio-code-erweiterungen.qmd
        - vscode/visual-studio-code-basics.qmd

    # - part: daten/index.qmd
    #   chapters:
    #     - daten/dictionary.qmd
    #     - daten/csv.qmd
    #     - daten/excel.qmd
    #     - daten/json.qmd

    - part: daten/index.qmd
      chapters:
        - text: "CSV-Daten"      
          href: daten/csv.qmd
        - text: "JSON-Daten"           
          href: daten/json.qmd   
        - text: "Relationale Datenbanken"
          href: daten/relational.qmd
        - text: "MySQ Datenbanken"
          href: daten/mysql.qmd          
        - text: "PostgreSQL"
          href: daten/postgresql.qmd 
        - text: "NoSQL"
          href: daten/nosql.qmd
        - text: "MongoDB"
          href: daten/mongodb.qmd    
        


    # - part: mysql/index.qmd
    #   chapters:
    #     - mysql/mysql-installation.qmd 
    #     - mysql/mysql-server.qmd
    #     - mysql/mysql-basics.qmd

    # - part: postgres/index.qmd
    #   chapters:
    #     - postgres/postgres-installation.qmd
    #     - postgres/postgres-server.qmd
    #     - postgres/postgres-basics.qmd
    #     - postgres/postgres-python.qmd

    # - part: mongodb/index.qmd
    #   chapters:
    #     - mongodb/mongodb-installation.qmd 
    #     - mongodb/mongodb-start-stop.qmd
    #     - mongodb/mongodb-basics.qmd  
    #     - mongodb/mongodb-python.qmd  
    #     - mongodb/mongodb-python-bilder.qmd  

    - part: github/index.qmd
      chapters:
        - github/github-git.qmd
        - github/github-setup.qmd
        - github/github-repo.qmd
        - github/github-organization.qmd
        - github/github-projects.qmd   


    - part: projekt/index.qmd
      chapters:
        - projekt/analytics.qmd


format:
  html:
    toc: true
    theme: cosmo
    css: theme.scss
    code-copy: true
    highlight-style: github-dark
    code-overflow: wrap
    author-meta: "Jan Kirenz"
    callout-appearance: simple