---
title: Bilddaten
lang: de
subtitle: Subtitle
author: Jan Kirenz
execute:
  eval: false
  echo: true
highlight-style: github-dark
format:
  revealjs: 
    toc: false
    toc-depth: 1
    embed-resources: false
    theme: [default, /style/custom.scss]
    incremental: true
    transition: slide
    background-transition: fade
    transition-speed: slow
    code-copy: true
    code-line-numbers: true
    smaller: false
    scrollable: true
    slide-number: c
    preview-links: auto
    css: /style/index.css
    chalkboard: 
      buttons: false
    logo: images/logo.png
    footer: Bilddaten | Jan Kirenz
jupyter: python3
---


Bilddaten sind eine wichtige Datenart in der Datenwissenschaft, besonders in Bereichen wie Computer Vision, Bilderkennung und maschinellem Lernen. Sie bestehen aus digitalen Informationen, die visuelle Inhalte repräsentieren. Bilddaten können in verschiedenen Formaten gespeichert werden, wie z.B. JPEG, PNG, BMP und TIFF.

Ein Bild besteht aus einer Matrix von Pixeln, wobei jeder Pixel einen Farbwert repräsentiert. Die häufigsten Farbmodelle sind RGB (Rot, Grün, Blau) und Graustufen. Im RGB-Modell wird die Farbe eines Pixels durch die Intensitätswerte der drei Grundfarben Rot, Grün und Blau bestimmt.

Ein RGB-Bild kann als eine dreidimensionale Matrix betrachtet werden, bei der die Dimensionen die Höhe, Breite und die drei Farbkanäle (Rot, Grün, Blau) sind. 

Hier zunächst ein einfaches Beispiel einer 3x3-Graustufen-Bildmatrix:

```{python}
import numpy as np

# Beispiel einer 3x3-Graustufen-Bildmatrix
image_matrix = np.array([
    [  0, 128, 255],
    [ 64, 192,  32],
    [255, 128,   0]
])

print(image_matrix)
```

Diese Matrix repräsentiert ein kleines Bild mit 3x3 Pixeln. Jeder Wert in der Matrix ist ein Graustufenwert zwischen 0 und 255. Um die Matrix als Bild anzuzeigen, können wir die Bibliothek Matplotlib verwenden:

```{python}
import matplotlib.pyplot as plt

# Bild anzeigen
plt.imshow(image_matrix, cmap='gray')
plt.colorbar()  # Farbleiste anzeigen
plt.show()
```

Dieses Beispiel zeigt, wie eine einfache Datenmatrix in ein Bild umgewandelt und angezeigt werden kann.

Für RGB-Bilder benötigen wir eine dreidimensionale Matrix, bei der die dritte Dimension die Farbkanäle (Rot, Grün, Blau) repräsentiert. Hier ist ein Beispiel einer 3x3-RGB-Bildmatrix:

```{python}
# Beispiel einer 3x3-RGB-Bildmatrix
rgb_image_matrix = np.array([
    [[255,   0,   0], [  0, 255,   0], [  0,   0, 255]],  # Erste Zeile: Rot, Grün, Blau
    [[255, 255,   0], [  0, 255, 255], [255,   0, 255]],  # Zweite Zeile: Gelb, Cyan, Magenta
    [[192, 192, 192], [128, 128, 128], [ 64,  64,  64]]   # Dritte Zeile: Verschiedene Grautöne
])

print(rgb_image_matrix)
```


Um die RGB-Matrix als Bild anzuzeigen, können wir ebenfalls Matplotlib verwenden:

```{python}
# RGB-Bild anzeigen
plt.imshow(rgb_image_matrix)
plt.show()
```

Dieses Beispiel zeigt, wie eine dreidimensionale Datenmatrix, die ein RGB-Bild repräsentiert, visualisiert werden kann.

