---
title: GitHub
lang: de
subtitle: Subtitle
author: Jan Kirenz
execute:
  eval: false
  echo: true
highlight-style: github-dark
format:
  revealjs: 
    toc: false
    toc-depth: 1
    embed-resources: false
    theme: [default, /style/custom.scss]
    incremental: true
    transition: slide
    background-transition: fade
    transition-speed: slow
    code-copy: true
    code-line-numbers: true
    smaller: false
    scrollable: true
    slide-number: c
    preview-links: auto
    css: /style/index.css
    chalkboard: 
      buttons: false
    logo: images/logo.png
    footer: GitHub | Jan Kirenz
jupyter: python3
---


[GitHub](https://github.com/) bietet Hosting für Softwareentwicklungsprojekte, die Git, ein Versionskontrollsystem, verwenden.

<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/w3jLJU7DT5E" title="YouTube-Video-Player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>  

<br>

GitHub ist wie ein kollaborativer Arbeitsbereich, in dem mehrere Entwickler ihre Projekte speichern, verwalten und Änderungen verfolgen können, ähnlich wie eine Online-Bibliothek digitaler Projekte.

Es ist eine Plattform, die es Entwicklern ermöglicht, gemeinsam an Softwareprojekten zu arbeiten, indem sie Git, ein verteiltes Versionskontrollsystem, nutzen. Mit GitHub können mehrere Entwickler gleichzeitig an verschiedenen Teilen eines Projekts arbeiten, Änderungen verfolgen und den Projektverlauf verwalten. Dies macht die Zusammenarbeit effizienter und die Verwaltung von Codeänderungen transparenter.

Zusätzlich zu den grundlegenden Funktionen der Versionskontrolle bietet GitHub zahlreiche Tools und Features, die die Softwareentwicklung erleichtern. GitHub ist daher nicht nur ein Speicherort für Code, sondern ein umfassendes Werkzeug für die kollaborative Entwicklung und das Projektmanagement.