---
title: Python
lang: de
subtitle: Subtitle
author: Jan Kirenz
execute:
  eval: false
  echo: true
highlight-style: github-dark
format:
  revealjs: 
    toc: false
    toc-depth: 1
    embed-resources: false
    theme: [default, custom.scss]
    incremental: true
    transition: slide
    background-transition: fade
    transition-speed: slow
    code-copy: true
    code-line-numbers: true
    smaller: false
    scrollable: true
    slide-number: c
    preview-links: auto
    css: style/index.css
    chalkboard: 
      buttons: false
   #logo: images/logo.png
    footer: Jan Kirenz
jupyter: python3
---


Python ist eine objektorientierte Programmiersprache, was bedeutet, dass es Daten als Objekte darstellt, die sowohl Informationen als auch Funktionalität enthalten.

Ein wichtiges Merkmal von Python ist, dass es interpretiert und nicht kompiliert wird. Der Interpreter führt den Code Zeile für Zeile aus, was besonders vorteilhaft für Aufgaben wie Datenanalyse und die Erstellung interaktiver, ausführbarer Dokumente wie Jupyter-Notebooks ist.

:::{.callout-note}
Python ist eine interpretierte Sprache, bei der der Interpreter ein Programm durch die Ausführung einer Anweisung nach der anderen ausführt.
:::

Über diese Kernfunktionalität hinaus bietet Python ein großes Ökosystem an Drittanbieter-Tools und -Modulen, wie das Jupyter-Notebook, die spezialisierte Funktionen für die Datenwissenschaft bereitstellen.