# MongoDB

**MongoDB** ist eine NoSQL-Datenbank, die für ihre Flexibilität und Skalierbarkeit bekannt ist. Sie speichert Daten in JSON-ähnlichen Dokumenten, was es einfach macht, komplexe Datenstrukturen zu handhaben.

Für die Arbeit mit der Datenbank nutzen wir die **MongoDB Shell** (`mongosh`). Diese bietet eine schnelle Möglichkeit, sich mit MongoDB zu verbinden und zu arbeiten. Sie ermöglicht das Abfragen von Daten, Konfigurieren von Einstellungen und Ausführen weiterer Aktionen mit einer modernen, erweiterbaren Befehlszeilenschnittstelle, die Syntaxhervorhebung, intelligente Autovervollständigung, kontextbezogene Hilfe und Fehlermeldungen umfasst.

## Installation

### Windows

1. **MongoDB herunterladen**:  
   Besuchen Sie die [offizielle MongoDB-Download-Seite](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-windows/#install-mongodb-community-edition) und laden Sie die aktuelle ("current") MongoDB Community Server-Version für Windows herunter.
   - Version: ... (current).
   - Platform: Windows x64
   - Package: msi

2. **Installation**:
   - Führen Sie das Installationsprogramm aus und folgen Sie den Anweisungen.
   - Wählen Sie "Complete" als Setup-Typ.
   - Aktivieren Sie die Option "Install MongoDB as a Service".

3. **MongoDB Shell (`mongosh`) herunterladen**:  
   Besuchen Sie die [MongoDB Shell Download-Seite](https://www.mongodb.com/try/download/shell) und laden Sie die aktuelle Version von MongoDB Shell herunter (wählen Sie als Plattform *Windows* und als Package *msi*).

Um MongoDB von jeder Eingabeaufforderung aus zugänglich zu machen, setzen wir nun eine Umgebungsvariable. Dadurch können Sie `mongod` und `mongo` von jeder Eingabeaufforderung aus ohne Angabe des vollständigen Pfades ausführen.

Hier ist eine detaillierte Anleitung, wie Sie die Umgebungsvariable unter Windows setzen können:

4. **Pfad zu `mongod.exe` und `mongosh.exe` ermitteln**:
   - Der Pfad ist in der Regel `C:\Program Files\MongoDB\Server\<Version>\bin`. Finden Sie den Pfad im Datei-Explorer und notieren Sie ihn.

5. **Umgebungsvariablen öffnen**:
   - Drücken Sie die Windows-Taste und geben Sie "Umgebungsvariablen" ein.
   - Wählen Sie "Umgebungsvariablen für dieses Konto bearbeiten" oder "Systemumgebungsvariablen bearbeiten" aus.

6. **Systemumgebungsvariablen bearbeiten**:
   - Im Fenster "Systemeigenschaften" klicken Sie auf die Schaltfläche "Umgebungsvariablen".

7. **Pfad-Variable bearbeiten**:
   - Im Abschnitt "Systemvariablen" suchen Sie die Variable "Path" und wählen Sie sie aus. Klicken Sie dann auf "Bearbeiten".

8. **Neuen Pfad hinzufügen**:
   - Klicken Sie auf "Neu" und fügen Sie den Pfad zu `mongod.exe` hinzu (z.B. `C:\Program Files\MongoDB\Server\<Version>\bin`).

9. **Änderungen speichern**:
   - Klicken Sie auf "OK", um alle Fenster zu schließen und die Änderungen zu speichern.

Um sicherzustellen, dass die Umgebungsvariablen korrekt gesetzt wurden, öffnen Sie eine neue Eingabeaufforderung und führen Sie die folgenden Befehle aus:

```sh
mongod --version
```

```sh
mongosh --version
```

Wenn beide Befehle die Versionsnummern von MongoDB und MongoDB Shell (mongosh) zurückgeben, wurde die Umgebungsvariable erfolgreich gesetzt

### macOS

Folgen Sie der Installationsanweisung der [MongoDB-Dokumentation](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/#install-mongodb-community-edition):

1. **Xcode Command-Line Tools installieren** (falls noch nicht installiert): Homebrew benötigt die Xcode Command-Line Tools von Apples Xcode.

   - Prüfen Sie im Terminal, ob XCode installiert ist (wenn Xcode installiert ist, wird die Version angezeigt. Wenn nicht, wird eine entsprechende Fehlermeldung angezeigt und Sie müssen XCode installieren):

   ```sh
   xcode-select --version
   ```

   - Falls notwendig, installieren Sie die Xcode Command-Line Tools mit folgendem Befehl im macOS Terminal:

   ```sh
   xcode-select --install
   ```

2. **Homebrew installieren** (falls noch nicht installiert):

   - Führen Sie diesen Befehl im Terminal aus, um den [Homebrew](https://brew.sh/)-Paketmanager zu installieren:

   ```sh
   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   ```

3. **MongoDB installieren**:

   - Laden Sie das offizielle Homebrew-Formular für MongoDB und die Datenbank-Tools herunter, indem Sie folgenden Befehl im macOS Terminal ausführen:

   ```sh
   brew tap mongodb/brew
   ```

   - Aktualisieren Sie Homebrew und alle vorhandenen Formeln:

   ```sh
   brew update
   ```

   - Um MongoDB zu installieren, führen Sie folgenden Befehl im macOS Terminal aus:

   ```sh
   brew install mongodb-community@7.0
   ```

Die Installation umfasst folgende Binärdateien:

- Der mongod-Server
- Der mongos-Sharded-Cluster-Query-Router
- Die MongoDB Shell, mongosh


## MongoDB starten und stoppen

### Windows

#### Starten

MongoDB sollte als Dienst automatisch gestartet werden, wenn Sie die Option "Install MongoDB as a Service" während der Installation aktiviert haben. 

Sie können den Dienst auch manuell starten, falls er nicht automatisch gestartet wurde oder falls Sie den Dienst neu starten möchten:


1. **Öffnen Sie die Dienstverwaltung**:
   - Drücken Sie die `Windows-Taste` + `R`, um das Ausführen-Dialogfeld zu öffnen.
   - Geben Sie `services.msc` ein und drücken Sie `Enter`.

2. **Finden Sie den MongoDB-Dienst**:
   - Im Fenster "Dienste" scrollen Sie nach unten, bis Sie den Dienst namens `MongoDB` finden.

3. **Starten Sie den Dienst**:
   - Klicken Sie mit der rechten Maustaste auf den `MongoDB`-Dienst und wählen Sie `Starten` aus dem Kontextmenü.

Alternativ können Sie den MongoDB-Dienst auch über die Eingabeaufforderung starten:

1. **Öffnen Sie die Eingabeaufforderung als Administrator**:
   - Drücken Sie die `Windows-Taste`, geben Sie `cmd` ein, klicken Sie mit der rechten Maustaste auf `Eingabeaufforderung` und wählen Sie `Als Administrator ausführen`.

2. **Führen Sie den folgenden Befehl aus, um den MongoDB-Dienst zu starten**:
   ```sh
   net start MongoDB
   ```

### Stoppen

Um MongoDB zu stoppen, können Sie entweder die Dienstverwaltung verwenden oder einen Befehl in der Eingabeaufforderung ausführen.

**So stoppen Sie den MongoDB-Dienst manuell:**

1. **Öffnen Sie die Dienstverwaltung**:
   - Drücken Sie die `Windows-Taste` + `R`, um das Ausführen-Dialogfeld zu öffnen.
   - Geben Sie `services.msc` ein und drücken Sie `Enter`.

2. **Finden Sie den MongoDB-Dienst**:
   - Im Fenster "Dienste" scrollen Sie nach unten, bis Sie den Dienst namens `MongoDB` finden.

3. **Stoppen Sie den Dienst**:
   - Klicken Sie mit der rechten Maustaste auf den `MongoDB`-Dienst und wählen Sie `Beenden` aus dem Kontextmenü.

Alternativ können Sie den MongoDB-Dienst auch über die Eingabeaufforderung stoppen:

1. **Öffnen Sie die Eingabeaufforderung als Administrator**:
   - Drücken Sie die `Windows-Taste`, geben Sie `cmd` ein, klicken Sie mit der rechten Maustaste auf `Eingabeaufforderung` und wählen Sie `Als Administrator ausführen`.

2. **Führen Sie den folgenden Befehl aus, um den MongoDB-Dienst zu stoppen**:
   ```sh
   net stop MongoDB
   ```

Durch das Starten und Stoppen des MongoDB-Dienstes können Sie sicherstellen, dass die Datenbank ordnungsgemäß läuft oder heruntergefahren wird, je nach Ihren Anforderungen.

### macOS

#### Starten

Nach der Installation von MongoDB können Sie den Datenbankdienst einfach mit Homebrew starten. Homebrew verwaltet Dienste wie MongoDB und ermöglicht es Ihnen, diese mit einfachen Befehlen zu starten und zu stoppen.

**So starten Sie den MongoDB-Dienst:**

1. **Öffnen Sie das Terminal**:
   - Sie finden das Terminal im Ordner "Dienstprogramme" innerhalb des Ordners "Programme" oder indem Sie `cmd + Leertaste` drücken und "Terminal" eingeben.

2. **Starten Sie den MongoDB-Dienst**:
   - Geben Sie den folgenden Befehl im Terminal ein und drücken Sie `Enter`:
   ```sh
   brew services start mongodb-community@7.0
   ```

   - Wenn alles korrekt eingerichtet ist, sehen Sie eine Bestätigungsmeldung, dass der Dienst gestartet wurde.

#### Überprüfen, ob MongoDB läuft

Um sicherzustellen, dass MongoDB korrekt gestartet wurde und läuft, können Sie eine Liste aller von Homebrew verwalteten Dienste anzeigen.

**So überprüfen Sie den Status von MongoDB:**

1. **Geben Sie den folgenden Befehl im Terminal ein und drücken Sie `Enter`**:
   ```sh
   brew services list
   ```

   - Dieser Befehl zeigt eine Liste aller Dienste an, die von Homebrew verwaltet werden, sowie deren aktuellen Status.

2. **Überprüfen Sie den Eintrag für `mongodb-community`**:
   - In der Liste sollten Sie `mongodb-community` sehen, gefolgt von der Versionsnummer und dem Status `started`. Dies zeigt an, dass MongoDB erfolgreich läuft.

#### Stoppen von MongoDB

Wenn Sie MongoDB beenden möchten, können Sie dies ebenfalls mit einem einfachen Homebrew-Befehl tun.

**So stoppen Sie den MongoDB-Dienst:**

1. **Geben Sie den folgenden Befehl im Terminal ein und drücken Sie `Enter`**:
   ```sh
   brew services stop mongodb-community@7.0
   ```

   - Auch hier sollte eine Bestätigungsmeldung erscheinen, dass der Dienst gestoppt wurde.

#### Zusammenfassung

- **Starten**: Um MongoDB zu starten, verwenden Sie den Befehl:
  ```sh
  brew services start mongodb-community@7.0
  ```

- **Prüfen**: Um zu überprüfen, ob MongoDB läuft, verwenden Sie den Befehl:
  ```sh
  brew services list
  ```

  - Suchen Sie in der Liste nach `mongodb-community` und stellen Sie sicher, dass der Status `started` angezeigt wird.

- **Stoppen**: Um MongoDB zu stoppen, verwenden Sie den Befehl:
  ```sh
  brew services stop mongodb-community@7.0
  ```

Diese Befehle bieten eine einfache Möglichkeit, den MongoDB-Dienst zu verwalten, ohne tiefere technische Kenntnisse über macOS-Dienste zu benötigen.