
# Grundlegende Nutzung von MongoDB

## MongoDB Shell

Um MongoDB zu nutzen, verbinden Sie mongosh mit der laufenden Instanz. Öffnen Sie ein neues Terminal und geben Sie den folgenden Befehl ein:

```sh
mongosh
```

Dieser Befehl startet die MongoDB Shell (mongosh) und verbindet sich mit der MongoDB-Instanz, die auf Ihrem System läuft. Wenn die Verbindung erfolgreich ist, sehen Sie die mongosh-Eingabeaufforderung, an der Sie Ihre MongoDB-Befehle eingeben können.

Falls Sie eine Fehlermeldung erhalten, prüfen Sie zunächst, ob [MongoDB](mongo-db-start-stop.qmd.qmd) auf Ihrem System läuft.

## Grundlegende Befehle

- **Datenbanken anzeigen**:
  ```sh
  show dbs
  ```

- **Datenbank auswählen oder erstellen**:
  ```sh
  use mydatabase
  ```

- **Sammlung (Collection) erstellen**:
  ```sh
  db.createCollection("mycollection")
  ```

- **Dokument einfügen**:
  ```sh
  db.mycollection.insertOne({name: "Jan", age: 44})
  ```

- **Dokumente abfragen**:
  ```sh
  db.mycollection.find()
  ```

## Python-Integration mit MongoDB

### Installation des MongoDB Python Treibers

Installieren Sie `pymongo`, den offiziellen MongoDB-Treiber für Python.

```{python}
!pip install pymongo
```

### Verbindung zu MongoDB herstellen

```{python}
import pymongo

# Verbindung zur MongoDB herstellen
client = pymongo.MongoClient("mongodb://localhost:27017/")

# Datenbank auswählen
db = client["mydatabase"]

# Sammlung auswählen
collection = db["mycollection"]

# Dokument einfügen
collection.insert_one({"name": "Alice", "age": 25})

# Dokumente abfragen
for doc in collection.find():
    print(doc)
```

