# MongoDB

MongoDB ist eine NoSQL-Datenbank, die für ihre Flexibilität und Skalierbarkeit bekannt ist. Sie speichert Daten in JSON-ähnlichen Dokumenten, was es einfach macht, komplexe Datenstrukturen zu handhaben.

Beispiel eines MongoDB-Dokuments:

```json
{
   "_id": ObjectId("5f8a7b2b9d3b2c1f4c6d8e7a"),
   "name": "Max Mustermann",
   "age": 30,
   "skills": ["Python", "Data Analysis", "Machine Learning"],
   "address": {
      "street": "Musterstraße 123",
      "city": "Musterstadt",
      "country": "Deutschland"
   }
}
```

Diese Strukturierung ermöglicht es, hierarchische Beziehungen und andere komplexe Datentypen ohne die Einschränkungen eines starren, tabellenbasierten Schemas darzustellen. Dadurch können Änderungen am Datenmodell schneller und effizienter umgesetzt werden.

Hauptmerkmale von MongoDB:

1. Flexibilität: MongoDB verwendet ein dokumentenorientiertes Modell, bei dem die Daten in Dokumenten gespeichert werden, die ähnliche Strukturen wie JSON haben. Dies ermöglicht eine hohe Flexibilität bei der Strukturierung der Daten, da jedes Dokument unterschiedliche Felder und Datentypen enthalten kann.


2. Skalierbarkeit: MongoDB ist darauf ausgelegt, horizontal zu skalieren, was bedeutet, dass die Datenbank einfach auf mehrere Server verteilt werden kann. Dies wird durch *Sharding* erreicht, eine Methode zur Verteilung von Daten über mehrere Maschinen, um sowohl die Speicherkapazität als auch die Verarbeitungsgeschwindigkeit zu erhöhen. 

3. Leistungsfähigkeit: Durch die Möglichkeit, Daten in einem einzigen Dokument zu speichern, kann MongoDB oft schnellere Schreib- und Leseoperationen durchführen als relationale Datenbanken. 


<!-- Die Hauptfunktionen von mongosh umfassen:

- **Syntaxhervorhebung**: Die Shell unterstützt Syntaxhervorhebung, die den Code lesbarer macht und die Erkennung von Fehlern erleichtert.
- **Intelligente Autovervollständigung**: Diese Funktion hilft bei der Eingabe von Befehlen und Parametern, indem sie Vorschläge macht und somit die Produktivität erhöht.
- **Kontextbezogene Hilfe**: mongosh bietet direkte Hilfe zu Befehlen und Optionen, was besonders nützlich für Einsteiger ist.
- **Fehlermeldungen**: Klare und präzise Fehlermeldungen helfen dabei, Probleme schnell zu identifizieren und zu beheben. -->

Um mit MongoDB zu beginnen, muss zunächst der MongoDB-Dienst gestartet und dann die MongoDB Shell geöffnet werden. Sobald die Shell geöffnet ist, können grundlegende Befehle ausgeführt werden, um Datenbanken und Sammlungen zu erstellen, Daten einzufügen und Abfragen auszuführen.

## MongoDB-Installation in Windows

In diesem Abschnitt wird die Installation der NoSQL-Datenbank MongoDB und der MongoDB Shell (mongosh) behandelt.

### Instalationsprozess

1. MongoDB herunterladen:  
   Die [offizielle MongoDB-Download-Seite](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-windows/#install-mongodb-community-edition) besuchen und die aktuelle ("current") MongoDB Community Server-Version für Windows herunterladen.
   - Version: ... (current).
   - Platform: Windows x64
   - Package: msi

2. Installation:
   - Das Installationsprogramm ausführen und den Anweisungen folgen.
   - "Complete" als Setup-Typ wählen.
   - Die Option "Install MongoDB as a Service" aktivieren.

3. MongoDB Shell (mongosh) herunterladen:  
   Die [MongoDB Shell Download-Seite](https://www.mongodb.com/try/download/shell) besuchen und die aktuelle Version von MongoDB Shell herunterladen (als Plattform *Windows* und als Package *msi* wählen).

Um MongoDB von jeder Eingabeaufforderung aus zugänglich zu machen, wird nun eine Umgebungsvariable gesetzt. Dadurch können `mongod` und `mongo` von jeder Eingabeaufforderung aus ohne Angabe des vollständigen Pfades ausgeführt werden.

### Umgebungsvariable setzen

Hier ist eine detaillierte Anleitung, wie die Umgebungsvariable unter Windows gesetzt werden kann:

1. Pfad zu `mongod.exe` und `mongosh.exe` ermitteln:
   - Der Pfad ist in der Regel `C:\Program Files\MongoDB\Server\<Version>\bin`. Den Pfad im Datei-Explorer finden und notieren (den Platzhalter <Version> mit der tatsächlichen Version ersetzen).

2. Umgebungsvariablen öffnen:
   - Die Windows-Taste drücken und "Umgebungsvariablen" eingeben.
   - "Umgebungsvariablen für dieses Konto bearbeiten" oder "Systemumgebungsvariablen bearbeiten" auswählen.

3. Systemumgebungsvariablen bearbeiten:
   - Im Fenster "Systemeigenschaften" auf die Schaltfläche "Umgebungsvariablen" klicken.

4. Pfad-Variable bearbeiten:
   - Im Abschnitt "Systemvariablen" die Variable "Path" suchen und auswählen. Dann auf "Bearbeiten" klicken.

5. Neuen Pfad hinzufügen:
   - Auf "Neu" klicken und den Pfad zu `mongod.exe` hinzufügen (z.B. `C:\Program Files\MongoDB\Server\<Version>\bin`).

6. Änderungen speichern:
   - Auf "OK" klicken, um alle Fenster zu schließen und die Änderungen zu speichern.

Um sicherzustellen, dass die Umgebungsvariablen korrekt gesetzt wurden, eine neue Eingabeaufforderung öffnen und die folgenden Befehle ausführen:

```sh
mongod --version
```

```sh
mongosh --version
```

Wenn beide Befehle die Versionsnummern von MongoDB und MongoDB Shell (mongosh) zurückgeben, wurde die Umgebungsvariable erfolgreich gesetzt.

## MongoDB starten und stoppen in Windows 

MongoDB sollte als Dienst automatisch gestartet werden, wenn die Option "Install MongoDB as a Service" während der Installation aktiviert wurde. In diesem Fall müssen zunächst keine weiteren Schritte unternommen werden. 

### MongoDB starten

Die folgenden Schritte sind nur dann auszuführen, falls MongoDB nicht automatisch gestartet wurde oder falls der Dienst neu gestartet werden soll:

1. Öffnen der Dienstverwaltung:
   - Die `Windows-Taste` + `R` drücken, um das Ausführen-Dialogfeld zu öffnen.
   - "services.msc" eingeben und Enter drücken.

2. MongoDB-Dienst finden:
   - Im Fenster "Dienste" nach unten scrollen, bis der Dienst namens "MongoDB" gefunden wird.

3. Dienst starten:
   - Mit der rechten Maustaste auf den `MongoDB`-Dienst klicken und "Starten" aus dem Kontextmenü wählen.

Alternativ kann der MongoDB-Dienst auch über die Eingabeaufforderung gestartet werden:

1. Eingabeaufforderung als Administrator öffnen:
   - Die Windows-Taste drücken, "Eingabeaufforderung" eingeben, mit der rechten Maustaste auf Eingabeaufforderung klicken und "Als Administrator ausführen" wählen.

2. Folgenden Befehl ausführen, um den MongoDB-Dienst zu starten:

```sh
net start MongoDB
```

### MongoDB stoppen

Um MongoDB zu stoppen, kann entweder die Dienstverwaltung verwendet oder ein Befehl in der Eingabeaufforderung ausgeführt werden.

So wird der MongoDB-Dienst manuell gestoppt:

1. Dienstverwaltung öffnen:
   - Die "Windows-Taste" + "R" drücken, um das Ausführen-Dialogfeld zu öffnen.
   - "services.msc" eingeben und Enter drücken.

2. MongoDB-Dienst finden:
   - Im Fenster "Dienste" nach unten scrollen, bis der Dienst namens "MongoDB" gefunden wird.

3. Dienst stoppen:
   - Mit der rechten Maustaste auf den `MongoDB`-Dienst klicken und "Beenden" aus dem Kontextmenü wählen.

Alternativ kann der MongoDB-Dienst auch über die Eingabeaufforderung gestoppt werden:

1. Eingabeaufforderung als Administrator öffnen:
   - Die "Windows-Taste" drücken, "Eingabeaufforderung" eingeben, mit der rechten Maustaste auf Eingabeaufforderung klicken und "Als Administrator ausführen" wählen.

2. Folgenden Befehl ausführen, um den MongoDB-Dienst zu stoppen:

```sh
net stop MongoDB
```

## MongoDB-Installation auf Mac

Wir folgen der Installationsanweisung der [MongoDB-Dokumentation](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/#install-mongodb-community-edition).

### Xcode Command-Line Tools

Zunächst müssen wir die Xcode Command-Line Tools von Apple installieren (falls noch nicht installiert). 

Im Terminal prüfen, ob XCode installiert ist (wenn Xcode installiert ist, wird die Version angezeigt. Wenn nicht, wird eine entsprechende Fehlermeldung angezeigt und XCode muss installiert werden):

```sh
xcode-select --version
```

Falls notwendig, die Xcode Command-Line Tools mit folgendem Befehl im macOS Terminal installieren:

```sh
xcode-select --install
```  

### Homebrew installieren

Homebrew ist ein beliebter Paketmanager für macOS, der die Installation von Software und Entwickler-Tools erheblich vereinfacht. Damit lassen sich viele nützliche Programme über die Kommandozeile installieren, die sonst möglicherweise kompliziert zu installieren wären.

Diesen Befehl im Terminal ausführen, um den [Homebrew](https://brew.sh/)-Paketmanager zu installieren:

```sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

### MongoDB intsallieren

MongoDB und die Datenbank-Tools herunterladen, indem folgender Befehl im macOS Terminal ausgeführt wird:

```sh
brew tap mongodb/brew
```

Homebrew und alle vorhandenen Formeln aktualisieren:

```sh
brew update
```

Um MongoDB zu installieren, folgenden Befehl im macOS Terminal ausführen:

```sh
brew install mongodb-community@7.0
```

Nachdem alles installiert wurde, eine neue Eingabeaufforderung öffnen und die folgenden Befehle ausführen:

Prüfung mongod-Server:

```sh
mongod --version
```

Die MongoDB Shell prüfen:

```sh
mongosh --version
```

Wenn bei beiden Befehlen eine Version angezeigt wird, war die Installation erfolgreich.

## MongoDB starten und stoppen auf Mac 

Nach der Installation von MongoDB kann der Datenbankdienst einfach mit Homebrew gestartet werden. Homebrew verwaltet Dienste wie MongoDB und ermöglicht es, diese mit einfachen Befehlen zu starten und zu stoppen.

### MongoDB starten

So wird der MongoDB-Dienst gestartet:

1. Terminal öffnen:
   - Das Terminal im Ordner "Dienstprogramme" innerhalb des Ordners "Programme" finden oder "cmd" + "Leertaste" drücken und "Terminal" eingeben.

2. MongoDB-Dienst starten:
   - Folgenden Befehl im Terminal eingeben und "Enter" drücken:

   ```sh
   brew services start mongodb-community@7.0
   ```

   - Wenn alles korrekt eingerichtet ist, erscheint eine Bestätigungsmeldung, dass der Dienst gestartet wurde.

Um sicherzustellen, dass MongoDB korrekt gestartet wurde und läuft, kann eine Liste aller von Homebrew verwalteten Dienste angezeigt werden.

So wird der Status von MongoDB überprüft:

1. Folgenden Befehl im Terminal eingeben und "Enter" drücken:

   ```sh
   brew services list
   ```

   - Dieser Befehl zeigt eine Liste aller Dienste an, die von Homebrew verwaltet werden, sowie deren aktuellen Status.

2. Den Eintrag für `mongodb-community` überprüfen:
   - In der Liste sollte `mongodb-community` zu sehen sein, gefolgt von der Versionsnummer und dem Status `started`. Dies zeigt an, dass MongoDB erfolgreich läuft.


### MongoDB stoppen

Wenn MongoDB beendet werden soll, kann dies mit einem einfachen Homebrew-Befehl getan werden.

Folgenden Befehl im Terminal eingeben und "Enter" drücken:

```sh
brew services stop mongodb-community@7.0
```

Es sollte eine Bestätigungsmeldung erscheinen, dass der Dienst gestoppt wurde.


## MongoDB Basics

In diesem Abschnitt werden die grundlegende Nutzung von MongoDB, einschließlich der Verbindung zur Datenbank, grundlegende Befehle und Datenbankmanipulation erläutert.

### Verbindung zur MongoDB-Instanz

Die MongoDB Shell (mongosh) ist das primäre Interface zur Interaktion mit der MongoDB-Datenbank. Sie ermöglicht es, Befehle direkt einzugeben und auszuführen. Um die MongoDB Shell zu starten und sich mit der laufenden MongoDB-Instanz zu verbinden, eine Kommandozeile (Eingabeaufforderung bzw. Terminal) öffnen und den folgenden Befehl eingeben:

```sh
mongosh
```

Wenn die Verbindung erfolgreich ist, erscheint die mongosh-Eingabeaufforderung:

```sh
test>
```

Falls eine Fehlermeldung auftritt, sicherstellen, dass [MongoDB auf dem System läuft](mongodb#mongodb-starten.qmd). 

### Datenbanken anzeigen

Um alle verfügbaren Datenbanken aufzulisten, folgenden Befehl verwenden:

```sh
show dbs
```

Dieser Befehl zeigt eine Liste aller Datenbanken, die auf der MongoDB-Instanz gespeichert sind.

### Datenbank auswählen oder erstellen

Um eine spezifische Datenbank auszuwählen oder zu erstellen, den `use`-Befehl verwenden:

```sh
use mydatabase
```

Dieser Befehl wechselt zur Datenbank `mydatabase`. Wenn die Datenbank noch nicht existiert, wird sie erstellt, sobald Daten eingefügt werden.

### Sammlung (Collection) erstellen

Um eine neue Sammlung innerhalb der aktuellen Datenbank zu erstellen, den `createCollection`-Befehl verwenden:

```sh
db.createCollection("mycollection")
```

Dieser Befehl erstellt eine neue Sammlung namens `mycollection`.

### Dokument einfügen

Um ein Dokument in eine Sammlung einzufügen, den `insertOne`-Befehl verwenden:

```sh
db.mycollection.insertOne({name: "Jan", age: 44})
```

Dieser Befehl fügt ein neues Dokument in die Sammlung `mycollection` ein.

### Dokumente abfragen

Um alle Dokumente in einer Sammlung abzufragen, den `find`-Befehl verwenden:

```sh
db.mycollection.find()
```

Dieser Befehl gibt alle Dokumente in der Sammlung `mycollection` zurück.

Beispiel-Output der Abfrage:

```sh
[
  { _id: ObjectId("666d5f5b50a5f96c3ed89649"), name: 'Jan', age: 44 },
  { _id: ObjectId("666d7727c1365bab40959889"), name: 'Alice', age: 25 }
]
```
<!-- 
### Weitere Befehle

- **Ein spezifisches Dokument abfragen**:
  ```sh
  db.mycollection.findOne({name: "Jan"})
  ```
  Dieser Befehl gibt das erste Dokument zurück, das den angegebenen Kriterien entspricht.

- **Dokumente aktualisieren**:
  ```sh
  db.mycollection.updateOne({name: "Jan"}, {$set: {age: 45}})
  ```
  Dieser Befehl aktualisiert das Alter von `Jan` auf 45.

- **Dokumente löschen**:
  ```sh
  db.mycollection.deleteOne({name: "Jan"})
  ```
  Dieser Befehl löscht das erste Dokument, das den angegebenen Kriterien entspricht.

- **Indizes erstellen**:
  ```sh
  db.mycollection.createIndex([("name", 1)])
  ```
  Dieser Befehl erstellt einen aufsteigenden Index auf dem Feld "name".

### Komplexere Abfragen

MongoDB unterstützt auch komplexere Abfragen und Aggregationen. Hier sind einige Beispiele:

- **Abfrage mit mehreren Bedingungen**:
  ```sh
  db.mycollection.find({age: {$gt: 30}, name: /^J/})
  ```
  Diese Abfrage findet alle Dokumente, bei denen das Alter größer als 30 ist und der Name mit "J" beginnt.

- **Sortieren von Ergebnissen**:
  ```sh
  db.mycollection.find().sort({age: -1})
  ```
  Dies sortiert die Ergebnisse absteigend nach Alter.

- **Aggregation Pipeline**:
  ```sh
  db.mycollection.aggregate([
    {$group: {_id: null, averageAge: {$avg: "$age"}}}
  ])
  ```
  Diese Aggregation berechnet das Durchschnittsalter aller Dokumente in der Sammlung. -->

## MongoDB Python-Integration

Die Integration von MongoDB in Python-Anwendungen ermöglicht es, die Vorteile von MongoDB in Data Science-Projekten zu nutzen. Hier wird erklärt, wie eine Umgebung eingerichtet und eine Verbindung zu MongoDB hergestellt wird.

### Umgebung erstellen

Um eine Umgebung einzurichten, diese Anweisungen basierend auf dem Betriebssystem befolgen:

1. Zugriff auf die Eingabeaufforderung oder das Terminal:
   - **Windows-Benutzer**: Die Anaconda-Eingabeaufforderung über das Startmenü öffnen.
   - **macOS-Benutzer**: Das Terminal unter Programme > Dienstprogramme öffnen oder nach "Terminal" suchen.  

2. Erstellen der Umgebung:
   - Den folgenden Befehl verwenden, um eine neue Conda-Umgebung namens `mongodb` mit Python 3.11 und pip zu erstellen:
   
   ```bash
   conda create --name mongodb python=3.11 pip
   ```

3. Aktivieren der Umgebung:
   - Sobald die Umgebung erstellt ist, diese aktivieren mit:
   
   ```bash
   conda activate mongodb
   ```

   - Die KOmmandozeile ändert sich, um anzuzeigen, dass die Umgebung `mongodb` aktiv ist.

4. Installieren der benötigten Bibliotheken:
   - Mit aktivierter Umgebung die Bibliotheken installieren:

   ```bash
   pip install pymongo gridfs pillow jupyter ipykernel pandas
   ```

   :::{.callout-note collapse="true" title="Erklärung der Bibliotheken"}
   - **pymongo**: Bietet eine Python-Schnittstelle zu MongoDB, einer NoSQL-Datenbank.
   - **pillow**: Eine Bibliothek für die Bildverarbeitung in Python, die das Öffnen, Bearbeiten und Speichern von Bilddateien unterstützt.
   - **jupyter**: Eine interaktive Entwicklungsumgebung zur Erstellung und Ausführung von Jupyter-Notebooks.
   - **ipykernel**: Eine Implementierung des Jupyter-Kernels für Python, die die Ausführung von Python-Code in Jupyter-Notebooks ermöglicht.
   - **pandas**: Eine leistungsfähige Datenanalysebibliothek für Python, die Datenmanipulation und -analyse vereinfacht.
   :::
   
   - Dieser Befehl ruft alle Pakete von PyPI ab und installiert sie.

### Verbindung herstellen

Um mit MongoDB zu arbeiten, muss in einem Jupyter Notebook eine Verbindung zur Datenbank hergestellt werden. Dies erfolgt in mehreren Schritten:

**Schritt 1: Importieren der pymongo-Bibliothek**

Zuerst muss die `pymongo`-Bibliothek importiert werden, die eine Schnittstelle zwischen Python und MongoDB bietet.

```python
import pymongo
```

**Schritt 2: Erstellen eines MongoDB-Clients**

Eine Verbindung zum MongoDB-Server erstellen. Der Standardanschluss für MongoDB ist `27017`.

```python
# Verbindung zur MongoDB herstellen
client = pymongo.MongoClient("mongodb://localhost:27017/")
```

Hier wird `localhost` verwendet, da der MongoDB-Server auf dem lokalen Rechner läuft. Wenn der Server auf einem Remote-Server läuft, `localhost` durch die IP-Adresse oder den Domain-Namen des Servers ersetzen.

**Schritt 3: Auswählen der Datenbank**

MongoDB organisiert Daten in Datenbanken. Um eine bestimmte Datenbank zu verwenden, auf diese wie folgt zugreifen:

```python
# Datenbank auswählen
db = client["mydatabase"]
```

Falls die Datenbank noch nicht existiert, wird sie erstellt, sobald ein Dokument eingefügt wird.

**Schritt 4: Auswählen der Sammlung**

Innerhalb einer Datenbank organisiert MongoDB Daten in Sammlungen (ähnlich wie Tabellen in SQL-Datenbanken). Eine Sammlung wie folgt auswählen:

```python
# Sammlung auswählen
collection = db["mycollection"]
```

Auch hier gilt: Falls die Sammlung noch nicht existiert, wird sie erstellt, sobald ein Dokument eingefügt wird.

**Schritt 5: Einfügen eines Dokuments**

Ein Dokument in MongoDB ist ein JSON-ähnliches Objekt. Ein Dokument wie folgt einfügen:

```python
# Dokument einfügen
result = collection.insert_one({"name": "Alice", "age": 25})
print(f"Eingefügtes Dokument ID: {result.inserted_id}")
```

Der Befehl `insert_one` fügt ein einzelnes Dokument in die Sammlung ein und gibt ein Ergebnisobjekt zurück, das die ID des eingefügten Dokuments enthält.

**Schritt 6: Abfragen von Dokumenten**

Um Dokumente aus einer Sammlung abzufragen, die Methode `find` verwenden. Diese gibt alle Dokumente in der Sammlung zurück:

```python
# Dokumente abfragen
for doc in collection.find():
    print(doc)
```

Dieser Code durchläuft alle Dokumente in der Sammlung und druckt sie aus. 

Hier der Output der Abfrage:

```sh
{'_id': ObjectId('666d5f5b50a5f96c3ed89649'), 'name': 'Jan', 'age': 44}
{'_id': ObjectId('666d7727c1365bab40959889'), 'name': 'Alice', 'age': 25}
```
<!-- 
### Weitere Funktionen

`pymongo` bietet viele weitere Funktionen, wie das Aktualisieren und Löschen von Dokumenten sowie das Erstellen von Indizes. Hier sind einige Beispiele:

**Dokument aktualisieren**

```python
# Dokument aktualisieren
result = collection.update_one({"name": "Alice"}, {"$set": {"age": 26}})
print(f"Anzahl der aktualisierten Dokumente: {result.modified_count}")
```

**Dokument löschen**

```python
# Dokument löschen
result = collection.delete_one({"name": "Alice"})
print(f"Anzahl der gelöschten Dokumente: {result.deleted_count}")
```

**Indizes erstellen**

```python
# Index erstellen
result = collection.create_index([("name", pymongo.ASCENDING)])
print(f"Erstellter Index: {result}")
```

**Komplexere Abfragen**

```python
# Abfrage mit Bedingungen
results = collection.find({"age": {"$gt": 25}})
for doc in results:
    print(doc)

# Sortierte Abfrage
results = collection.find().sort("age", pymongo.DESCENDING)
for doc in results:
    print(doc)

# Aggregation
pipeline = [
    {"$group": {"_id": None, "avg_age": {"$avg": "$age"}}}
]
result = list(collection.aggregate(pipeline))
print(f"Durchschnittsalter: {result[0]['avg_age']}")
```

Diese zusätzlichen Funktionen ermöglichen eine umfassendere Interaktion mit der MongoDB-Datenbank und bieten leistungsfähige Werkzeuge für die Datenanalyse und -manipulation in Data Science-Projekten. -->