# MySQL

MySQL, das sowohl als "My S-Q-L" als auch als "My Sequel" ausgesprochen wird, ist ein relationales Datenbankverwaltungssystem (RDBMS), das zur Verwaltung von Daten in relationalen Datenbanken dient. Es verwendet die Structured Query Language (SQL) für verschiedene Aufgaben wie Datenverwaltung, -manipulation und -abfrage.

MySQL Workbench bietet eine grafische Oberfläche für Datenbankverwaltung und SQL-Entwicklung. Es integriert visuelle Werkzeuge für Datenmodellierung, SQL-Entwicklung und umfassende Datenbankverwaltung.

Hauptkomponenten der MySQL Workbench:

- **Toolbar**: Oben befindliche Leiste mit Schaltflächen für häufige Aktionen wie neue Abfrage-Tabs oder Ausführen von Abfragen.
- **Seitenleiste**: Links platzierte Leiste für Zugriff auf Instanzverwaltung, Leistungsüberwachung und weitere Funktionen.
- **Abfrage-Tab**: Zentraler Bereich zum Schreiben und Ausführen von SQL-Abfragen.
- **Ausgabebereich**: Unterhalb des Abfrage-Editors zur Anzeige von Abfrageergebnissen oder Servermeldungen.

## MySQL-Installation in Windows

Folgende Schritte führen durch die Installation von MySQL und MySQL Workbench:

1. Installer herunterladen
   - Auf der [MySQL Downloadseite](https://dev.mysql.com/downloads/installer/) Windows als Plattform wählen.
   - MySQL-Installer für Windows in Version 8.0.37 herunterladen.

2. Installer ausführen
   - Heruntergeladene Datei ausführen und bei Sicherheitsabfrage "Ja" wählen.

3. Setup-Typ auswählen
   - "Custom" als Setup-Typ wählen für spezifische Komponentenauswahl.

4. Produkte und Features auswählen
   - 'MySQL Server' und 'MySQL Workbench' zur Installation auswählen.

5. Installation durchführen
   - Bildschirmanweisungen zur Installation der gewählten Komponenten befolgen.

6. MySQL Server konfigurieren
   - Root-Passwort einrichten, Benutzerkonten erstellen, Netzwerkoptionen und Windows-Dienst konfigurieren.

7. Installation abschließen
   - Setup beenden, um die MySQL-Installation abzuschließen.

## MySQL-Installation auf Mac

Installationsschritte für MySQL und MySQL Workbench auf Mac:

1. MySQL herunterladen und installieren
   - [MySQL Downloadseite](https://dev.mysql.com/downloads/mysql/) besuchen, macOS wählen.
   - DMG-Datei für macOS (Version 8.0.36) herunterladen und installieren.

2. MySQL Workbench installieren
   - [MySQL Workbench Downloadseite](https://dev.mysql.com/downloads/workbench/) aufrufen.
   - Passende Version für macOS herunterladen und installieren.

## Server einrichten

Nach der Installation erfolgt die Verbindung zum MySQL-Server über MySQL Workbench:

1. MySQL Workbench starten
   - Anwendung aus der Programmübersicht öffnen.

   :::{.callout-tip collapse="true" title="Tipp für Windows-Nutzer"}
   Falls MySQL Workbench während der anfänglichen Einrichtung des MySQL Servers nicht enthalten war, kann es separat installiert werden:

   [MySQL Workbench Downloadseite](https://dev.mysql.com/downloads/workbench/) öffnen und passende Version für das Betriebssystem auswählen.
   :::


2. Neue Verbindung erstellen
   - Auf "+" im Bereich "MySQL Connections" klicken.
   - Verbindungsdetails eingeben:
     - Name: `local-connection`
     - Hostname: `localhost`
     - Port: `3306`
     - Benutzername: Meist 'root'
     - Passwort: "Store in Vault" wählen und Passwort eingeben, welches während der Installation vergeben wurde.
   - "Test Connection" zur Überprüfung klicken.

3. Verbindung speichern
   - Bei erfolgreicher Verbindung auf "OK" klicken.

## SQL-Basics in MySQL

Nachfolgend behandeln wir einige typische Aufgaben in MySQL Workbench, die bei der Arbeit mit Datenbanken anfallen.

### Datenbank erstellen

1. Mit MySQL-Instanz verbinden (`local-connection`).
2. Neues Abfrage-Tab öffnen (auf das "+"-Symbol oben klicken)
3. SQL-Befehle eingeben und ausführen (auf das Blitzsymbol (⚡) klicken, um den Befehl auszuführen):

   ```sql
   DROP DATABASE IF EXISTS `db_data`;
   CREATE DATABASE `db_data`;
   USE `db_data`;
   ```


   :::{.callout-note collapse="true" title="Erklärung der SQL-Befehle"}
   Der SQL-Code führt drei Operationen durch:

   1. **DROP DATABASE IF EXISTS `db_data`;**
      - Dieser Befehl löscht die Datenbank `db_data`, falls sie existiert. Dies ist nützlich, um sicherzustellen, dass wir mit einer neuen Datenbank arbeiten, indem eine eventuell vorhandene Datenbank mit demselben Namen entfernt wird.

   2. **CREATE DATABASE `db_data`;**
      - Dieser Befehl erstellt eine neue Datenbank mit dem Namen `db_data`. Dies legt die Basis für eine neue Datenbank, in der wir Tabellen und andere Datenbankobjekte erstellen können.

   3. **USE `db_data`;**
      - Dieser Befehl setzt die neu erstellte Datenbank `db_data` als die aktuell verwendete Datenbank. Alle nachfolgenden SQL-Befehle werden auf dieser Datenbank ausgeführt.
   :::


4. Schema-Liste aktualisieren zur Anzeige der neuen Datenbank (Schema-Liste befindet sich auf der linken Seite der Benutzer-Oberfläche)

### Tabelle erstellen

Als Beispieldaten erstellen wir eine Tabelle zu einer Marketingkampagne:


1. Neues Abfrage-Tab öffnen.
2. SQL zur Tabellenerstellung ausführen:

   ```sql
   CREATE TABLE campaigns (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      start_date DATE,
      end_date DATE,
      budget DECIMAL(10, 2),
      channel VARCHAR(255)
      );
   ```

   :::{.callout-note collapse="true" title="Erklärung der Tabellendefinition"}
   
   Der obige SQL-Befehl erstellt eine neue Tabelle namens `campaigns`. Hier ist eine Aufschlüsselung jeder Spaltendefinition:

   - **id**: Eine Spalte namens `id`, die den Datentyp `INT` (integer) verwendet und automatisch inkrementiert wird (d.h. 1, 2, 3, ...), was sich gut als Primärschlüssel eignet.
   - **name**: Eine Spalte zur Speicherung der Kampagnennamen als Text, um eine Zeichenkette von bis zu 255 Zeichen zu halten. Die `NOT NULL`-Einschränkung stellt sicher, dass jede Zeile einen Namen haben muss.
   - **start_date** und **end_date**: Diese Spalten speichern die Start- und Enddaten der Kampagnen mit dem Datentyp `DATE`.
   - **budget**: Eine Spalte für das Budget jeder Kampagne, die `DECIMAL(10, 2)` verwendet, um bis zu 10 Stellen mit 2 Dezimalstellen zu ermöglichen.
   - **channel**: Eine Spalte, um das verwendete Medium der Kampagne anzugeben, die Zeichenfolgen von bis zu 255 Zeichen speichern kann.
   :::


3. Befehl ausführen und Schema-Ansicht überprüfen.

### Werte einfügen

Wir gehen wie folgt vor, um die Tabelle mit Daten zu füllen:


1. In neuem Abfrage-Tab SQL-Befehl ausführen:

   ```sql
   INSERT INTO campaigns (name, start_date, end_date, budget, channel) VALUES
   ('Winter Sale', '2023-12-01', '2023-12-31', 5000.00, 'Email'),
   ('Summer Festival', '2023-06-01', '2023-06-15', 10000.00, 'Social Media'),
   ('Back to School', '2023-08-01', '2023-08-20', 7500.00, 'TV');
   ```

   :::{.callout-note collapse="true" title="Erklärung der Insert-Anweisung"}
   Dieser SQL-Befehl fügt Daten in die `campaigns`-Tabelle ein. Jede Zeile von Werten entspricht einer anderen Marketingkampagne:

   - **Erste Zeile**: Fügt eine Kampagne namens "Winter Sale" ein, die vom 1. bis 31. Dezember 2023 läuft, mit einem Budget von $5000 und dem Kanal "Email".
   - **Zweite Zeile**: Fügt "Summer Festival" ein, eine kürzere Kampagne vom 1. bis 15. Juni 2023, mit einem höheren Budget von $10000 und dem Kanal "Social Media".
   - **Dritte Zeile**: Fügt die "Back to School"-Kampagne vom 1. bis 20. August 2023 hinzu, mit einem Budget von $7500, vermarktet über "TV".

   Jeder Satz von Werten ist in Klammern eingeschlossen und durch Kommas getrennt, um verschiedene Kampagnen zu unterscheiden.
   :::

### Werte abrufen

Um die Daten zu überprüfen:

1. SELECT-Abfrage in neuem Tab ausführen:

   ```sql
   SELECT * FROM campaigns;
   ```

   :::{.callout-note collapse="true" title="Erklärung der SELECT-Abfrage"}
   Der SQL-Befehl ruft alle Spalten aus allen Zeilen in der `campaigns`-Tabelle ab. Er ist nützlich, um alle eingegebenen Daten in der Tabelle anzuzeigen, sicherzustellen, dass die Einträge korrekt sind, und um weitere Datenanalysen oder Berichte zu ermöglichen.
   :::


Erwartetes Ergebnis:

| id | name            | start_date | end_date   | budget   | channel      |
|----|-----------------|------------|------------|----------|--------------|
| 1  | Winter Sale     | 2023-12-01 | 2023-12-31 | 5000.00  | Email        |
| 2  | Summer Festival | 2023-06-01 | 2023-06-15 | 10000.00 | Social Media |
| 3  | Back to School  | 2023-08-01 | 2023-08-20 | 7500.00  | TV           |


