# Python 

Python kann direkt von der offiziellen Python-Website oder über einen Paketmanager wie Anaconda installiert werden, der zusätzliche Tools bietet und das Paketmanagement vereinfacht.

Dieses Kapitel konzentriert sich auf die Installation von Python direkt von der offiziellen Quelle.

## Installation

### Windows

1. **Installationsprogramm herunterladen**: Navigieren Sie zur [Python-Website](https://www.python.org/downloads/) und laden Sie die neueste Version für Ihre Windows-Version herunter (normalerweise Windows-Installer 64-Bit).
2. **Installationsprogramm ausführen**: Klicken Sie mit der rechten Maustaste auf das heruntergeladene Installationsprogramm und wählen Sie "Als Administrator ausführen". Stellen Sie sicher, dass Sie das Kästchen "Add Python 3.x to PATH" am unteren Rand des Installationsfensters markieren, um sicherzustellen, dass Python zu den Umgebungsvariablen Ihres Systems hinzugefügt wird (Dies ist entscheidend, damit Python von jedem Verzeichnis im System aus über die Kommandozeile aufgerufen werden kann. Ohne diese Einstellung müssten Sie den vollständigen Pfad zur Python-Installation angeben, um Python auszuführen, was unpraktisch und fehleranfällig ist).
3. **Anpassung der Installation (optional)**: Sie können die Installation anpassen, indem Sie auf "Customize installation" klicken. Dies ermöglicht es Ihnen, spezifische Funktionen wie Dokumentation, pip, Tests usw. auszuwählen.
4. **Installation starten**: Klicken Sie auf "Install Now", um den Installationsvorgang zu starten.

### Mac

1. **Installationsprogramm herunterladen**: Navigieren Sie zur [Python-Website](https://www.python.org/downloads/) und laden Sie die neueste Version herunter.
2. **Python installieren**: Öffnen Sie die heruntergeladene `.pkg`-Datei und folgen Sie den Anweisungen zur Installation von Python. Der Installationsassistent führt Sie durch die notwendigen Schritte.

<!-- 3. Python zum PATH hinzufügen: Der Installationsassistent sollte diesen Schritt erledigen, aber Sie können dies überprüfen, indem Sie ein Terminal öffnen und `echo $PATH` eingeben. Stellen Sie sicher, dass das Verzeichnis, in dem Python installiert ist, in der Ausgabe erscheint. -->

## Überprüfung der Installation

Nach der Installation überprüfen Sie, ob Python korrekt installiert wurde, indem Sie eine Kommandozeile öffnen (Terminal auf macOS, Eingabeaufforderung oder PowerShell auf Windows) und eingeben:

```bash
python --version
```

Dieser Befehl sollte die Version von Python anzeigen, die Sie installiert haben.

::: {.callout-caution title="Unterschiedliche Python-Version" collapse="true"}
Wenn Sie bereits Python oder eine Python-Distribution wie Anaconda installiert haben, kann das Ausführen von `python --version` in Ihrem Terminal eine andere Python-Version anzeigen als die, die Sie gerade installiert haben. Diese Abweichung tritt auf, weil Ihr System mehrere Python-Installationen gleichzeitig verwalten kann. Der Terminalbefehl wählt die Version, die zuerst in der PATH-Variable des Systems erscheint, was möglicherweise nicht die zuletzt installierte Version ist.

Dies ist eine gängige Situation und kein Grund zur Sorge. Wir werden dieses Thema in einem späteren Kapitel erneut behandeln und besprechen, wie Sie mehrere Python-Versionen effektiv verwalten können, um sicherzustellen, dass Sie verschiedene Python-Umgebungen je nach Bedarf für Ihre Projekte auswählen und verwenden können.
:::

## Fehlerbehebung 

- **Python nicht erkannt**: Wenn die Kommandozeile den Befehl `python` nicht erkennt, liegt es möglicherweise daran, dass Python nicht zu Ihrem PATH hinzugefügt wurde. Überprüfen Sie die Installationsschritte noch einmal, um sicherzustellen, dass Sie die Option ausgewählt haben, Python zu Ihrem PATH hinzuzufügen.

- **Berechtigungsfehler während der Installation**: Dies tritt normalerweise unter Windows auf und kann behoben werden, indem das Installationsprogramm als Administrator ausgeführt wird.