# Basics


## Installation

Install the latest version of the Anaconda Distribution:

::: {.callout-important title="To do"}

- [Anaconda installation](https://www.anaconda.com/download)

:::

After you have installed Anaconda, you can update it. The following commands will update all packages in the default "base" environment to the latest version but will not update Python:

::: {.callout-important title="To do"}

- On *Windows* open the Start menu and open an ["Anaconda Command Prompt"](https://conda.io/projects/conda/en/latest/user-guide/getting-started.html#starting-conda). 
- On *macOS* or *Linux* open a [terminal window](https://conda.io/projects/conda/en/latest/user-guide/getting-started.html#starting-conda).
- In your terminal, type: `conda update --all`
:::

Now follow the steps described in the next section.


### Anaconda environment

After you have installed and updated Anaconda, you can install the modules you need for a specific lab in a new environment. 


::: {.callout-important title="To do"}

- Go to [GitHub course environments](https://github.com/kirenz/environments)
- Follow the instructions in the GitHub repo and install the environment `env-lab` 
:::




#### Install or update Modules

Take a look at all the modules in your environment:

```bash
conda list
```

Make sure that you use `scikit-learn` in version 1.0.2 or higher. If this is not the case, update Anaconda. If you only want to **update specific modules**, use conda update and the name of the module (e.g., scikit-learn)

```bash
conda update scikit-learn
```

If you want to **install new modules** in your environment, you should always use conda (and not the package installer for Python: [pip](https://pypi.org/project/pip/)). Here is an example of how to install scikit-learn [see conda documentation](https://anaconda.org/anaconda/scikit-learn)

```bash
conda install scikit-learn
```

Or, if you want to install a specific version

```bash
conda install scikit-learn=1.0.2
```

Finally, take a look at the [Anaconda Cheat Sheet](https://docs.conda.io/projects/conda/en/latest/_downloads/843d9e0198f2a193a3484886fa28163c/conda-cheatsheet.pdf) which provides a list of useful commands.





### Miniforge {#sec-miniforge}

As an alternative to Anaconda, you can also use the open-source project [Miniforge](https://github.com/conda-forge/miniforge).

Miniforge is a small, bootstrap version of the data science platform Anaconda that includes only Python, the open source package management system [conda](https://docs.conda.io/en/latest/) and a small number of other useful packages. 

Miniforge also uses Anaconda's package manager `conda`, which makes it easy to manage multiple data environments that can be maintained and run separately without interference from each other (in so called virtual environments).

:::{.callout-note}
Miniforge is an community-led alternative to the data science platforms Anaconda and Miniconda, provided by Anaconda, Inc.
:::

Compared to Anaconda, Miniforge provides more up-to-date packages, and is more user-friendly. Therefore, I recommend using Miniforge for data science projects.

::: {.callout-note}
## To do

Install the latest version of the Miniforge

- [Miniforge installation tutorial](https://kirenz.github.io/codelabs/codelabs/miniforge-setup/#0)

:::




# Visual Studio Code {#sec-vscode}

## Basics

Visual Studio Code (also called Code) is a powerful source code editor which runs on your desktop and is available for Windows, macOS and Linux. It comes with a rich ecosystem of extensions for Python.

:::{.callout-note}
Visual Studio Code is a code editor that can be used with a variety of programming languages including Python.
:::

<br>

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/KMxo3T_MTvY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br>

## Installation

Install VS Code:

::: {.callout-important}
## To do
- [Install Code](https://code.visualstudio.com/)
:::

## Install extensions

The features that Visual Studio Code includes out-of-the-box are just the start. VS Code extensions let you add languages, debuggers, and tools to your installation to support your development workflow.

Let's install some important extensions:

::: {.callout-important}
## To do
- [Visual Studio Code Extensions](https://vscode.dev/profile/github/94d1b9a0184dec88655f9622c87b866d)
:::

## Jupyter Notebooks

We usually work with Jupyter Notebook files in VS Code:

::: {.callout-important}
## To do
- [Learn how to use Jupyter Notebooks in VS Code](https://code.visualstudio.com/docs/datascience/jupyter-notebooks)
:::

To use a specific Anaconda environment as Jupyter kernel, select the kernel (e.g. `lab`) using the [kernel picker](https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_create-or-open-a-jupyter-notebook) in the top right of VS Code.



## Optional tutorials

Some resources to get familiar with VS Code:

- [Take a look at the intro videos](https://code.visualstudio.com/docs/getstarted/introvideos)
- [Data Science in VS Code tutorial](https://code.visualstudio.com/docs/datascience/data-science-tutorial)
- Pro tips: [25 VS Code Productivity Tips and Speed Hacks](https://www.youtube.com/watch?v=ifTF3ags0XI)


