# Installation

## Windows

1. **MongoDB herunterladen**:  
   Besuchen Sie die [offizielle MongoDB-Download-Seite](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-windows/#install-mongodb-community-edition) und laden Sie die aktuelle ("current") MongoDB Community Server-Version für Windows herunter.
   - Version: ... (current).
   - Platform: Windows x64
   - Package: msi

2. **Installation**:
   - Führen Sie das Installationsprogramm aus und folgen Sie den Anweisungen.
   - Wählen Sie "Complete" als Setup-Typ.
   - Aktivieren Sie die Option "Install MongoDB as a Service".

3. **MongoDB Shell (`mongosh`) herunterladen**:  
   Besuchen Sie die [MongoDB Shell Download-Seite](https://www.mongodb.com/try/download/shell) und laden Sie die aktuelle Version von MongoDB Shell herunter (wählen Sie als Plattform *Windows* und als Package *msi*).

Um MongoDB von jeder Eingabeaufforderung aus zugänglich zu machen, setzen wir nun eine Umgebungsvariable. Dadurch können Sie `mongod` und `mongo` von jeder Eingabeaufforderung aus ohne Angabe des vollständigen Pfades ausführen.

Hier ist eine detaillierte Anleitung, wie Sie die Umgebungsvariable unter Windows setzen können:

4. **Pfad zu `mongod.exe` und `mongosh.exe` ermitteln**:
   - Der Pfad ist in der Regel `C:\Program Files\MongoDB\Server\<Version>\bin`. Finden Sie den Pfad im Datei-Explorer und notieren Sie ihn.

5. **Umgebungsvariablen öffnen**:
   - Drücken Sie die Windows-Taste und geben Sie "Umgebungsvariablen" ein.
   - Wählen Sie "Umgebungsvariablen für dieses Konto bearbeiten" oder "Systemumgebungsvariablen bearbeiten" aus.

6. **Systemumgebungsvariablen bearbeiten**:
   - Im Fenster "Systemeigenschaften" klicken Sie auf die Schaltfläche "Umgebungsvariablen".

7. **Pfad-Variable bearbeiten**:
   - Im Abschnitt "Systemvariablen" suchen Sie die Variable "Path" und wählen Sie sie aus. Klicken Sie dann auf "Bearbeiten".

8. **Neuen Pfad hinzufügen**:
   - Klicken Sie auf "Neu" und fügen Sie den Pfad zu `mongod.exe` hinzu (z.B. `C:\Program Files\MongoDB\Server\<Version>\bin`).

9. **Änderungen speichern**:
   - Klicken Sie auf "OK", um alle Fenster zu schließen und die Änderungen zu speichern.

Um sicherzustellen, dass die Umgebungsvariablen korrekt gesetzt wurden, öffnen Sie eine neue Eingabeaufforderung und führen Sie die folgenden Befehle aus:

```sh
mongod --version
```

```sh
mongosh --version
```

Wenn beide Befehle die Versionsnummern von MongoDB und MongoDB Shell (mongosh) zurückgeben, wurde die Umgebungsvariable erfolgreich gesetzt

## macOS

Folgen Sie der Installationsanweisung der [MongoDB-Dokumentation](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/#install-mongodb-community-edition):

1. **Xcode Command-Line Tools installieren** (falls noch nicht installiert): Homebrew benötigt die Xcode Command-Line Tools von Apples Xcode.

   - Prüfen Sie im Terminal, ob XCode installiert ist (wenn Xcode installiert ist, wird die Version angezeigt. Wenn nicht, wird eine entsprechende Fehlermeldung angezeigt und Sie müssen XCode installieren):

   ```sh
   xcode-select --version
   ```

   - Falls notwendig, installieren Sie die Xcode Command-Line Tools mit folgendem Befehl im macOS Terminal:

   ```sh
   xcode-select --install
   ```

2. **Homebrew installieren** (falls noch nicht installiert):

   - Führen Sie diesen Befehl im Terminal aus, um den [Homebrew](https://brew.sh/)-Paketmanager zu installieren:

   ```sh
   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   ```

3. **MongoDB installieren**:

   - Laden Sie das offizielle Homebrew-Formular für MongoDB und die Datenbank-Tools herunter, indem Sie folgenden Befehl im macOS Terminal ausführen:

   ```sh
   brew tap mongodb/brew
   ```

   - Aktualisieren Sie Homebrew und alle vorhandenen Formeln:

   ```sh
   brew update
   ```

   - Um MongoDB zu installieren, führen Sie folgenden Befehl im macOS Terminal aus:

   ```sh
   brew install mongodb-community@7.0
   ```

Öffnen Sie -nachdem alles installiert wurde- eine neue Eingabeaufforderung und führen Sie die folgenden Befehle aus:

Prüfung mongod-Server:

```sh
mongod --version
```

Die MongoDB Shell: mongosh

```sh
mongosh --version
```

Wenn bei beiden Befehlen eine Version angezeigt wird, war die Installation erfolgreich.