# Anaconda Distribution

Die Anaconda Distribution ist ein umfangreiches Softwarepaket, das Python und eine Vielzahl wichtiger Data Science-Tools beinhaltet. Sie stellt eine zentrale Plattform für die Arbeit mit Daten dar und erleichtert den Einstieg in die Welt der Data Science erheblich.

Die Anaconda Distribution umfasst die folgende Hauptkomponenten:

1. *Python*: Eine leistungsstarke und vielseitige Programmiersprache, die sich besonders gut für Data Science eignet.

2. *Conda*: Ein leistungsfähiges Paket- und Umgebungsmanagement-System.

3. *Über 250 vorinstallierte Pakete*: Darunter befinden sich wichtige Software-Pakete für Data Science und KI.

4. *Anaconda Navigator*: Eine grafische Benutzeroberfläche zur einfachen Verwaltung von Umgebungen und Paketen. Außerdem bietet es Zugriff auf verschiedene Data Science-Tools (bspw. Jupyter Notebook).


::: {.callout-note}
Die Anaconda Distribution ermöglicht es, schnell und unkompliziert mit Data Science-Projekten zu beginnen, ohne sich um die Installation und Konfiguration einzelner Pakete kümmern zu müssen. Dies ist besonders wertvoll für Einsteiger/innen, da es den Einstieg in die Data Science erheblich erleichtert.
:::

Anaconda, Inc. ist das Unternehmen hinter der Anaconda Distribution. Es wurde 2012 gegründet, ursprünglich unter dem Namen Continuum Analytics. Das Unternehmen hat sich zum Ziel gesetzt, die Arbeit mit Daten zu demokratisieren und Data Science für ein breites Spektrum an Personen zugänglich zu machen. Mit der Entwicklung der Anaconda Distribution hat das Unternehmen einen bedeutenden Beitrag zur Data Science-Community geleistet.


## Anaconda in Windows installieren

1. Zunächst besuchen wir die [Anaconda-Download-Seite](https://www.anaconda.com/download/success).
2. Hier wählen wir die Windows-Version aus.
3. Wir laden den grafischen Installer herunter.
4. Nach dem Download klicken wir mit der rechten Maustaste auf den Installer und wählen "Als Administrator ausführen".
5. Im Setup-Assistenten klicken wir uns durch die verschiedenen Bildschirme:
   - Wir stimmen den Geschäftsbedingungen zu.
   - Als Installationstyp wählen wir "Nur für mich" (empfohlen).
   - Wir wählen den gewünschten Zielordner für die Installation.
   - Wichtig: Wir aktivieren die Option "Anaconda zu meiner PATH-Umgebungsvariablen hinzufügen".
   - Ebenso aktivieren wir "Anaconda als meine Standard-Python-Version registrieren".
6. Mit einem Klick auf "Installieren" starten wir den Installationsprozess.
7. Nach Abschluss der Installation klicken wir auf "Fertig stellen".

## Anaconda auf Mac installieren

1. Wir öffnen die [Anaconda-Download-Seite](https://www.anaconda.com/download/success).
2. Hier wählen wir die passende macOS-Version aus (hier eine Übersicht über die [Mac-Ausführungen](https://support.apple.com/en-us/116943)):
   - Für Geräte mit Apple-Chip wählen wir "Apple Silicon".
   - Für ältere Geräte wählen wir die Intel-Version.
3. Wir laden den grafischen Installer herunter.
4. Nach dem Download auf die heruntergeladene `.pkg`-Datei doppelklicken.
5. Im Installationsassistenten folgen wir den Anweisungen:
   - Lizenzvereinbarung lesen und akzeptieren.
   - Als Zielort wählen wir unser Home-Verzeichnis (z.B. `/Users/benutzername`).
6. Mit einem Klick auf "Installieren" starten wir den Prozess.
7. Nach Abschluss schließen wir den Installer.

## Anaconda überprüfen und aktualisieren

Um sicherzustellen, dass Anaconda korrekt installiert wurde:

1. Wir öffnen ein Eingabeaufforderungsfenster (Windows) oder Terminal (macOS/Linux).
2. Hier geben wir folgenden Befehl ein:

   ```bash
   conda --version
   ```

3. Wenn Anaconda korrekt installiert ist, sehen wir die Versionsnummer im Terminal.

Es ist ratsam, nach der Installation alle Standardpakete zu aktualisieren:

   ```bash
   conda update --all
   ```

Wir folgen den Anweisungen, um die Aktualisierung abzuschließen.


Mit der erfolgreichen Installation von Anaconda haben wir nun Zugriff auf Jupyter Notebook, eine webbasierte Umgebung zum Schreiben und Ausführen von Python-Code. Diese Umgebung wird uns in unseren Data Science-Projekten begleiten und bietet mehr Möglichkeiten als die einfache IDLE-Umgebung.

In den nächsten Kapiteln werden wir lernen, wie wir Jupyter Notebook effektiv für unsere Data Science-Aufgaben nutzen können.