# Umgebungen

Umgebungen ("environments") sind isolierte Arbeitsbereiche, in denen Sie Python-Pakete separat für jedes Projekt installieren und verwalten können. Sie helfen Ihnen, verschiedene Abhängigkeiten für unterschiedliche Projekte zu verwalten, um Kompatibilität zu gewährleisten und Konflikte zu vermeiden.

Vorteile:

- **Abhängigkeitsverwaltung**: Eine Umgebung stellt sicher, dass die richtige Version jedes Pakets für Ihr Projekt verfügbar ist, wodurch Fehler durch inkompatible Versionen vermieden werden.
  
- **Projekttrennung**: Sie können verschiedene Projekte mit unterschiedlichen Paketanforderungen haben und so Konflikte vermeiden. Beispielsweise kann ein Data-Science-Projekt spezifische Versionen von Datenanalysebibliotheken erfordern, während ein Webentwicklungsprojekt andere Bedürfnisse haben könnte.
  
- **Entwicklung benutzerdefinierter Module**: Wenn Sie Ihre eigenen Module erstellen, helfen Umgebungen dabei, diese in Ihre Projekte zu integrieren, ohne Ihre globale Python-Installation zu beeinträchtigen.


## Umgebung erstellen

Um eine Umgebung einzurichten, befolgen Sie diese Anweisungen basierend auf Ihrem Betriebssystem:


1. Zugriff auf die Eingabeaufforderung oder das Terminal:
   - **Windows-Benutzer**: Öffnen Sie die Anaconda-Eingabeaufforderung über das Startmenü.
   - **macOS-Benutzer**: Öffnen Sie das Terminal unter Programme > Dienstprogramme oder durch die Suche nach "Terminal".  

2. Erstellen der Umgebung:
   - Verwenden Sie den folgenden Befehl, um eine neue Conda-Umgebung namens `basics` mit Python 3.11 und pip zu erstellen:
   
   ```bash
   conda create --name basics python=3.11 pip
   ```

   - Geben Sie bei `Proceed ([y]/n)?`ein `y` ein, um die Installtion zu starten.
   
   ::: {.callout-note}
   pip ist ein Paketverwaltungstool für Python. Es steht für "Pip Installs Packages" oder "Pip Installs Python" und wird verwendet, um Python-Pakete aus dem [Python Package Index (PyPI)](https://pypi.org/) zu installieren und zu verwalten. Mit pip kann man Pakete installieren, aktualisieren und deinstallieren.
   :::

3. Aktivieren der Umgebung:
   - Sobald die Umgebung erstellt ist, aktivieren Sie sie mit:
   
   ```bash
   conda activate basics
   ```

   - Die Eingabeaufforderung ändert sich, um anzuzeigen, dass die Umgebung `basics` aktiv ist.

4. Installieren der benötigten Bibliotheken:
   - Mit aktivierter Umgebung installieren Sie die Bibliotheken:

   ```bash
   pip install numpy pandas openpyxl matplotlib seaborn altair jupyter ipykernel
   ```
   
   :::{.callout-note collapse="true" title="Erklärung der Pakete"}
   - **numpy**: Eine leistungsfähige Bibliothek für numerische Berechnungen.
   - **pandas**: Ein wichtiges Tool zur Datenmanipulation und -analyse. 
   - **openpyxl**: Ermöglicht das Lesen und Schreiben von Excel-Dateien (.xlsx) und wird oft in Verbindung mit Pandas verwendet, um Excel-Daten zu bearbeiten.
   - **matplotlib**: Eine weitverbreitete Bibliothek zur Erstellung von Visualisierungen in Python.
   - **seaborn**: Aufbauend auf matplotlib, bietet diese Bibliothek statistische Datenvisualisierungen.
   - **altair**: Eine Visualisierungsbibliothek, die interaktive Grafiken erstellt.
   - **jupyter**: Ein Open-Source-Webanwendungs-Tool, das es ermöglicht, Dokumente zu erstellen und zu teilen, die Live-Code, Gleichungen, Visualisierungen und narrativen Text enthalten.
   - **ipykernel**: Ermöglicht die Integration von Jupyter Notebooks mit dem IPython-Kernel, was das Ausführen von Python-Code innerhalb der Jupyter-Umgebung unterstützt.
   :::

   - Dieser Befehl ruft alle Pakete von PyPI ab und installiert sie.

   ::: {.callout-note}
   Obwohl Sie Pakete auch mit `conda install` installieren können, verwenden wir ausschließlich `pip`, um mögliche Konflikte zwischen Conda- und Pip-installierten Paketen zu vermeiden. Dieser Ansatz stellt eine konsistente und zuverlässige Verwaltung von Abhängigkeiten in Ihrer Python-Umgebung sicher.
   :::

5. Überprüfen der Paketinstallation:
   - Nach der Installation öffnen Sie ein Jupyter Notebook und überprüfen, ob die Pakete verfügbar sind, indem Sie sie in Python importieren.


   ::: {.callout-note}
   Um die Nutzung der Funktionen und Methoden der Bibliotheken in Ihrem Code zu erleichtern, importieren wir sie häufig mit kürzeren, standardisierten Aliasen (die Verwendung dieser Standard-Aliase verbessert die Lesbarkeit des Codes und reduziert den Schreibaufwand).
   :::

   ```python
   import numpy as np
   import pandas as pd
   import matplotlib.pyplot as plt
   import seaborn as sns
   import altair as alt
   ```
  
   - Wenn keine Fehler auftreten, wurden die Bibliotheken korrekt installiert.
   
   :::{.callout-tip collapse="true" title="Erklärung der Pakete"} 

   **NumPy (`np`)**: Der Alias `np` wird weit verbreitet verwendet und ermöglicht einen prägnanten Zugriff auf NumPys Funktionen für numerische Berechnungen.

   **Pandas (`pd`)**: Der Alias `pd` bietet eine Kurzform für Pandas' leistungsstarke Datenmanipulationstools.

   **Matplotlib (`plt`)**: Der Alias `plt` vereinfacht das Aufrufen der Funktionen von Matplotlib zum Plotten, Erstellen von Abbildungen und Anpassen von Grafiken.

   **Seaborn (`sns`)**: Der Alias `sns` erleichtert den Zugriff auf Seaborns statistische Datenvisualisierungstools, die nahtlos mit Matplotlib integriert sind.

   **Altair (`alt`)**: Der Alias `alt` ermöglicht einen schnellen Zugriff auf Altairs  Visualisierungssyntax für interaktives Plotten.
   :::

6. Deaktivieren der Umgebung:
   - Wenn Sie fertig sind oder zur Basisumgebung zurückkehren möchten, deaktivieren Sie die aktuelle Umgebung:

   ```bash
   conda deactivate
   ```

Das Erstellen einer separaten Umgebung für Python-Grundlagen stellt sicher, dass Ihr Arbeitsbereich isoliert und stabil bleibt.