# Arbeitsbereich einrichten

Bevor Sie mit dem Programmieren in Python beginnen, stellen wir sicher, dass Sie einen ordnungsgemäß konfigurierten Arbeitsbereich haben.

## Anaconda Navigator starten

1. Anaconda Navigator starten:
   - Öffnen Sie den Anaconda Navigator aus dem Anwendungsordner auf macOS oder dem Startmenü auf Windows.

2. Jupyter Notebook öffnen:
   - Finden Sie im Anaconda Navigator das Jupyter Notebook und klicken Sie auf 'Launch', um es in Ihrem Webbrowser zu öffnen.

## Jupyter Notebook einrichten

1. Wählen Sie die Umgebung aus:
   - Verwenden Sie im Jupyter Notebook das Dropdown-Menü "New" (oben rechts), um die `python-basics` Umgebung auszuwählen.

2. Erstellen Sie ein neues Notebook:
   - Klicken Sie auf 'New' und wählen Sie `python-basics` unter dem Abschnitt Notebooks, um ein neues Notebook zu starten. Erstellen Sie in diesem Notebook eine neue Markdown-Zelle, um dem Notebook einen Titel zu geben (z.B. Python basics):

   ```markdown
   # Python basics
   ```

3. Speichern Sie das Notebook:
   - Speichern Sie Ihr Notebook im `code` Ordner (siehe unsere [Ordnerstruktur](../first-steps/command-line.qmd) Erklärung) mit einem aussagekräftigen Namen (z.B. `python-basics.ipynb`).

## Jupyter Notebook herunterladen

In den kommenden Abschnitten haben Sie die Möglichkeit, den Inhalt als Notebook herunterzuladen. Nach dem Herunterladen können Sie es in Ihrem `code` Ordner speichern und das Notebook in Jupyter öffnen.

:::{.callout-tip}
Der Download-Link befindet sich am Anfang jedes Dokuments, das Code-bezogene Inhalte enthält.
:::