# Arbeitsbereich vorbereiten

Bevor wir mit dem Programmieren in Python beginnen, stellen wir sicher, dass wir einen ordnungsgemäß konfigurierten Arbeitsbereich haben.

## Anaconda Navigator starten

1. Anaconda Navigator starten:
   - Anaconda Navigator aus dem Anwendungsordner auf macOS oder dem Startmenü auf Windows öfnnen.

2. Jupyter Notebook öffnen:
   - Im Anaconda Navigator bei Jupyter Notebook auf 'Launch' klicken, um die Anwendung im Webbrowser zu öffnen.

## Jupyter Notebook starten

1. In der Web-Oberfläche von Jupyter zum *code*-Verzeichnis (siehe die Erklärung zur [Ordnerstruktur](../erste-schritte/projektumgebung.qmd)) navigieren.
2. Oben rechts auf "New" klicken und "Notebook" auswählen, um ein neues Notebook zu erstellen.
3. Nun öffnet sich ein Fenster in welchem wir den Kernel (eine Python-Instanz) auswählen können. Wir wählen die eben installierte `basics`-Umgebung aus (siehe [diese Anleitung](python-arbeitsbereich.qmd)).
4. In dem Notebook eine neue Markdown-Zelle erstellen, um dem Notebook einen Titel zu geben (z.B. Python basics):

   ```markdown
   # Python basics
   ```
5. Notebook speichern:
   - Notebook im `code` Ordner (siehe unsere [Ordnerstruktur](../erste-schritte/projektumgebung.qmd) Erklärung) mit einem aussagekräftigen Namen (z.B. *python-basics.ipynb*) speichern.

