# Python-Integration

Dieses Tutorial führt Sie durch den Prozess des Übertragens von Daten aus einem pandas DataFrame in eine PostgreSQL-Datenbank. Stellen Sie sicher, dass PostgreSQL installiert und die Datenbank auf Ihrem Rechner geöffnet ist, bevor Sie beginnen.

## Python-Umgebung

Richten Sie zuerst eine isolierte Python-Umgebung mit Anaconda ein:

1. Erstellen Sie eine neue Umgebung (wenn Sie detailliertere Erklärungen benötigen, lesen Sie dieses Kapitel über die [Erstellung von Umgebungen](../python/python-arbeitsbereich.qmd)):

```bash
conda create -n postgres python=3.11 pip
```

2. Aktivieren Sie die Umgebung:

```bash
conda activate postgres
```

3. Installieren Sie die notwendigen Pakete: Wir benötigen `psycopg2-binary` für die PostgreSQL-Konnektivität, `sqlalchemy` für SQL-Operationen und `pandas` für die Datenmanipulation.

```bash
pip install psycopg2-binary sqlalchemy ipykernel jupyter pandas
```

## Datenbankverbindung

Um von Python aus mit Ihrer PostgreSQL-Datenbank zu interagieren, richten Sie eine Verbindung mit SQLAlchemy ein:

1. Starten Sie PostgreSQL: Stellen Sie sicher, dass Ihre PostgreSQL-Instanz läuft.

2. Importieren Sie die Bibliotheken und erstellen Sie eine Engine: Die Engine ist Ihr Zugang zur Datenbank. Ersetzen Sie Platzhalter durch Ihre tatsächlichen Datenbank-Anmeldedaten.

```python
import sqlalchemy as sa

# Ersetzen Sie die Platzhalter durch Ihre Datenbank-Anmeldedaten
engine = sa.create_engine('postgresql://your_username:your_password@localhost:your_port/your_database')
```

Sie müssen die links aufgeführten Platzhalter in der oben gezeigten Funktion ersetzen:

- `your_username`: Typischerweise `postgres`
- `your_password`: Ihr Datenbank-Passwort
- `your_port`: Üblicherweise `5432`
- `your_database`: Standardmäßig `postgres` (Sie sollten die von uns [bereits erstelle](postgres-pgadmin4#eine-datenbank-erstellen.qmd) Datenbank `db_data` verwenden)

Hier ein Beispiel, in welchem als Passwort der Begriff `mysecretpassword`verwendet wurde:

```python
import sqlalchemy as sa

# Ersetzen Sie die Platzhalter durch Ihre Datenbank-Anmeldedaten
engine = sa.create_engine('postgresql://postgres:mysecretpassword@localhost:5432/db_data')
```

Für weitere Details zur Konfiguration der Engine, siehe die [SQLAlchemy-Dokumentation](https://docs.sqlalchemy.org/en/14/core/engines.html).

## Daten in PostgreSQL schreiben

Mit der eingerichteten Verbindung übertragen wir nun Daten von einem pandas DataFrame nach PostgreSQL:

1. Laden Sie die Daten in einen DataFrame:

   ```python
   import pandas as pd

   # Laden der Daten aus einer CSV-Datei
   df = pd.read_csv("https://raw.githubusercontent.com/kirenz/datasets/master/gapminder.csv")
   ```

   :::{.callout-note collapse="true" title="Erklärung des Codes"}
   Der Python-Code verwendet die Bibliothek pandas, um Daten aus einer CSV-Datei zu laden:

   1. **Importieren der pandas-Bibliothek**:
      - **pandas** ist eine weit verbreitete Bibliothek in Python, die leistungsstarke, benutzerfreundliche Datenstrukturen und Datenanalyse-Tools bietet.
      - Mit `import pandas as pd` importieren wir die Bibliothek und geben ihr das Alias `pd`, um den Code kürzer und lesbarer zu machen.

   2. **Laden der Daten aus einer CSV-Datei**:
      - **`pd.read_csv`**: Diese Methode wird verwendet, um eine CSV-Datei in einen pandas DataFrame zu laden.
      - **URL der CSV-Datei**: `"https://raw.githubusercontent.com/kirenz/datasets/master/gapminder.csv"` ist die URL der CSV-Datei, die die Daten enthält. Die Methode kann Daten direkt von einer URL laden, ohne dass die Datei lokal gespeichert werden muss.
      - **`df`**: Der resultierende DataFrame wird in der Variablen `df` gespeichert. Ein DataFrame ist eine tabellarische Datenstruktur, die sowohl Zeilen- als auch Spaltenbeschriftungen hat, ähnlich wie eine Tabelle in einer Datenbank oder ein Datenblatt in Excel.
   :::

2. Schreiben Sie den DataFrame nach PostgreSQL:
   Verwenden Sie die Methode `to_sql`, um die Daten in eine neue Tabelle namens `gapminder` zu schreiben.

   ```python
   df.to_sql('gapminder', engine, if_exists='replace')
   ```
   :::{.callout-note collapse="true" title="Erklärung des Codes"}
   Der Python-Code verwendet die Methode `to_sql` von pandas, um einen DataFrame in eine SQL-Datenbank zu schreiben:

   1. **`df.to_sql`**:
      - Diese Methode schreibt den DataFrame `df` in eine SQL-Datenbank.

   2. **`'gapminder'`**:
      - Dies ist der Name der Tabelle, in die die Daten geschrieben werden. In diesem Fall wird die Tabelle `gapminder` genannt.

   3. **`engine`**:
      - Dies ist die SQLAlchemy-Engine, die die Verbindung zur Datenbank darstellt. Die Engine enthält alle notwendigen Informationen, um sich mit der Datenbank zu verbinden und Befehle auszuführen.

   4. **`if_exists='replace'`**:
      - Diese Option gibt an, was geschehen soll, wenn die Tabelle `gapminder` bereits in der Datenbank existiert. 
      - **`replace`**: Diese Option sorgt dafür, dass die vorhandene Tabelle gelöscht und durch die neue Tabelle ersetzt wird, die aus dem DataFrame `df` erstellt wird.
   :::


   Dies sollte als Ergebnis `704` ausgeben (die Anzahl der Zeilen, die in die neue Tabelle geschrieben wurden.).

3. Überprüfen Sie die Tabelle in der Datenbank:
   Führen Sie eine Abfrage in der Datenbank aus, um zu bestätigen, dass die Tabelle existiert.

   ```python
   with engine.connect() as connection:
         tables = connection.execute(sa.text("SELECT table_name FROM information_schema.tables WHERE table_schema='public'"))
         for table in tables:
            print(table[0])
   ```

   :::{.callout-note collapse="true" title="Erklärung des Codes"}
   Der Code öffnet eine Verbindung zu einer SQL-Datenbank mithilfe der SQLAlchemy-Engine.

   - Innerhalb des `with`-Blocks wird sichergestellt, dass die Verbindung nach Abschluss des Blocks automatisch geschlossen wird.
   - Der Befehl `connection.execute` führt eine SQL-Abfrage aus, die die Namen aller Tabellen im `public`-Schema der Datenbank aus der `information_schema.tables`-Tabelle abruft.
   - Diese Abfrage gibt eine Liste der Tabellennamen zurück.
   - Diese Liste wird in einer Schleife durchlaufen.
   - Innerhalb der Schleife wird der Name jeder Tabelle mit `print(table[0])` auf der Konsole ausgegeben.
   :::

   Dies sollte ausgeben: `gapminder` (d.h. die Tabelle gapminder ist in der Datenbank enthalten)


4. Optional: Entfernen Sie die Tabelle:
   Wenn Sie die Tabelle aus der Datenbank löschen möchten:

   ```python
   sql = sa.text("DROP TABLE IF EXISTS gapminder")

   with engine.connect() as connection:
         connection.execute(sql)
   ```

   :::{.callout-note collapse="true" title="Erklärung des Codes"}
   Der Code definiert eine SQL-Abfrage, die überprüft, ob die Tabelle `gapminder` existiert, und sie löscht, falls sie vorhanden ist. Diese Abfrage wird in der Variablen `sql` gespeichert.

   - Ein `with`-Block wird verwendet, um eine Verbindung zur SQL-Datenbank mithilfe der SQLAlchemy-Engine zu öffnen. Der `with`-Block stellt sicher, dass die Verbindung nach Abschluss des Blocks automatisch geschlossen wird.
   - Innerhalb des `with`-Blocks wird die SQL-Abfrage `sql` mit dem Befehl `connection.execute(sql)` ausgeführt.
   - Diese Ausführung löscht die Tabelle `gapminder`, falls sie in der Datenbank existiert.
   :::


Sie sollten die Tabelle nun auch in PgAdmin4 sehen. Öffnen Sie dafür die Anwendung und navigieren Sie zu der Tabelle.