# SQL & Python

Dieses Tutorial führt Sie durch den Prozess des Übertragens von Daten aus einem pandas DataFrame in eine PostgreSQL-Datenbank. Es ist eine wertvolle Fähigkeit für datengetriebene Projekte in Python, die es Ihnen ermöglicht, Ihre Daten effektiv zu speichern und zu verwalten.

Stellen Sie sicher, dass [PostgreSQL installiert](sql-postgresql.qmd) und auf Ihrem Rechner ausgeführt wird, bevor Sie beginnen.

## Python-Umgebung

Richten Sie zuerst eine isolierte Python-Umgebung mit Anaconda ein:

1. Erstellen Sie eine neue Umgebung (wenn Sie detailliertere Erklärungen benötigen, lesen Sie dieses Kapitel über die [Erstellung von Umgebungen](../python/python-environment-basics.qmd)):

```bash
conda create -n postgres python=3.11 pip
```

2. Aktivieren Sie die Umgebung:

```bash
conda activate postgres
```

3. Installieren Sie die notwendigen Pakete: Wir benötigen `psycopg2-binary` für die PostgreSQL-Konnektivität, `sqlalchemy` für SQL-Operationen und `pandas` für die Datenmanipulation.

```bash
pip install psycopg2-binary sqlalchemy ipykernel jupyter pandas
```

## Datenbankverbindung

Um von Python aus mit Ihrer PostgreSQL-Datenbank zu interagieren, richten Sie eine Verbindung mit SQLAlchemy ein:

1. Starten Sie PostgreSQL: Stellen Sie sicher, dass Ihre PostgreSQL-Instanz läuft.

2. Importieren Sie die Bibliotheken und erstellen Sie eine Engine: Die Engine ist Ihr Zugang zur Datenbank. Ersetzen Sie Platzhalter durch Ihre tatsächlichen Datenbank-Anmeldedaten.

```python
import sqlalchemy as sa

# Ersetzen Sie die Platzhalter durch Ihre Datenbank-Anmeldedaten
engine = sa.create_engine('postgresql://your_username:your_password@localhost:your_port/your_database')
```

Hier müssen Sie Folgendes ersetzen:

- `your_username`: Typischerweise `postgres`
- `your_password`: Ihr Datenbank-Passwort
- `your_port`: Üblicherweise `5432`
- `your_database`: Standardmäßig `postgres` (Sie können auch db_data verwenden)

Für weitere Details zur Konfiguration der Engine, siehe die [SQLAlchemy-Dokumentation](https://docs.sqlalchemy.org/en/14/core/engines.html).

## Daten in PostgreSQL schreiben

Mit der eingerichteten Verbindung übertragen wir nun Daten von einem pandas DataFrame nach PostgreSQL:

1. Laden Sie die Daten in einen DataFrame:
```python
import pandas as pd

# Laden der Daten aus einer CSV-Datei
df = pd.read_csv("https://raw.githubusercontent.com/kirenz/datasets/master/gapminder.csv")
```

2. Schreiben Sie den DataFrame nach PostgreSQL:
   Verwenden Sie die Methode `to_sql`, um die Daten in eine neue Tabelle namens `gapminder` zu schreiben.

```python
df.to_sql('gapminder', engine, if_exists='replace')
```

Dies sollte ausgeben: 704.

3. Überprüfen Sie die Tabelle in der Datenbank:
   Führen Sie eine Abfrage in der Datenbank aus, um zu bestätigen, dass die Tabelle existiert.

```python
with engine.connect() as connection:
      tables = connection.execute(sa.text("SELECT table_name FROM information_schema.tables WHERE table_schema='public'"))
      for table in tables:
           print(table[0])
```

Dies sollte ausgeben: gapminder


4. Optional: Entfernen Sie die Tabelle:
   Wenn Sie die Tabelle aus der Datenbank löschen müssen:

```python
sql = sa.text("DROP TABLE IF EXISTS gapminder")

with engine.connect() as connection:
      connection.execute(sql)
```


Werfen Sie als Nächstes einen Blick auf die Tabelle mit [PgAdmin4](sql-postgresql.qmd).